browser:
  browserName: chrome
  headlessBrowser: false
  webElementTimeout: 10

environment:
  dev:
    envName: dev
    appUrl: https://www.selenium.dev/
    active: false

  test:
    envName: test
    appUrl: http://146.59.32.4/index.php
    active: true

  preprod:
    envName: preprod
    appUrl: https://seleniumui.moderntester.pl/
    active: false